# Workflow di deploy verso il sito di produzione (Altervista)

name: prod-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out so the job can access code
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server_prod }}
          username: ${{ secrets.ftp_user_prod }}
          password: ${{ secrets.ftp_password_prod }}
          server-dir: /
